#!/bin/bash

cat << 'EOF'

Here are some useful commands:
  Enter the tmux session where the services run
  (note: tmux prefix key has been configured to backtick)
    └── tmux a

  Install Ubuntu packages
    └── sudo apt update && sudo apt install <pkg>

  Install Python packages
    └── pip install <pkg>

EOF
